S02-2 Move semantics and exception handling
balintkiss501/pti-msc-2015-zv pull request #1
Opened 2017-06-28 14:52 UTC by dobreffandras

2017-06-28 14:53 UTC, dobreffandras commented on s02/2.md
> +Hiba: Eljárás előfeltételének megsértése miatt, vagy bármely más nem kívánt működésből adódó állapot.
Ez ilyen saját fejből jött. Nem tudom mennyire megfelelő

2017-06-29 16:59 UTC, balintkissdev requested changes

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +**Memória szegements**: Operációs rendszer $\Rightarrow$ minden programnak egy területet tart fenn a memóriából.
"Memória szegmens"

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +
* Alias egy változónévhez
* Analógia: mint Linux alatt a szimbolikus linkek

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +
Ökölszabály

* Ahol lehet, használj referenciákat
* Ahol muszáj, használj pointereket (de akkor már inkább smart pointereket a mai világban)

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +* _globális terület_: konstansok, globális változók, melyek végig jelen vannak
* _data segment (globális terület)_
    + konstansok, globális változók, statikus lokális változók
    + program indulásakor le van foglalva nekik terület (még ha nincsenek is inicializálva)
    + program futásának végéig jelen vannak
* _stack (verem)_
    + lokális változók
    + automatikusan jönnek létre definiáláskor, lokális scope végén pedig automatikusan felszabadulnak
    + függvények memóriaterületeit stack frame-eknek hívjuk
        - függvényhíváskor hívó függvény (_caller_) stack frame-jének elmentése és hívott függvény (_callee_) stack frame-jének beállítása (_function prologoue_)
        - paraméterek mozgatása regiszterekbe
        - függvény végrehajtása
        - végén return value írása regiszterbe
        - hívott függvény stack frame pop-olása és visszatérés hívó függvénybe (_function epilogue_)
* _heap (kupac)_
    + futásidőben dinamikusan lefoglalható (általában a legnagyobb része a programnak)
    + akkor, amikor változó mérete csak futásidőben határozható meg vagy mérete stack overflow-t eredményezne
    + lassabb elérni, mint a stack-et

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +double d1 = 10, d2 = 50;
Suggestion: nem lehet ilyen varázsbetűket megjegyezni. Helyette ez a javaslatom:

```cpp
double const_reference &d1r = d1;                         // konstans referencia
double const * pointer_to_const = &d1;                    // mutató konstansra
double * const const_pointer = &d1;                       // konstans mutató
// konstans mutató konstans értékre
double const * const const_pointer_to_const_value = &d1;  

const_reference = 100;                    // HIBA, az érték nem módosítható
*pointer_to_const = 50;                   // HIBA, az érték nem módosítható
*const_pointer = 50;                      // az érték módosítható
*const_pointer_to_const_value = 50;       // HIBA
pointer_to_const = &d2;                   // átállíthatjuk más memóriacímre
const_pointer = &d2;                      // HIBA, a mutató nem állítható át
const_pointer_to_const_value = &d2;       // HIBA
```

2017-06-29 16:59 UTC, balintkissdev commented on s02/2.md
> +
Tehát a következők szerint érdemes a paraméterátadást használni:

* _érték szerinti_:
    + ```f(int x)```
    + a függvény **nem módosítja a paramétert**
    + **könnyű másolni**
    + Ökölszabály: ha a paraméter mérete legfeljebb 2- vagy 3 szó (_word_), azaz 32-bit, akkor érdemes érték szerint átadni
        - egyszerű típusok esetén ajánlott, mint pl.: `int`, `double`, `char`, `bool`, stb.
        - Saját osztályok, `std::string` és a különböző STL konténerek nem ajánlottak
* _pointer szerinti_:
    + ```f(int * x)```
    + a függvény **módosítja a paramétert**,
    + **költséges a másolás**,
    + a **NULL valid** érték
* _konstans pointer szerinti_:
    + ```f(const * int x)```
    + a függvény **nem módosítja a paramétert**,
    + **költséges a másolás**, 
    + a **NULL valid** érték
* _referencia szerinti_: 
    + ```f(int& x)```
    + a függvény **módosítja a paramétert**
    + **költséges a másolás**,
    + a **NULL nem valid** érték
    + használható kiementként is
* _konstans referencia szerinti_:
    + ```f(const int& x)```
    + a függvény **nem módosítja a paramétert**,
    + **költséges a másolás**
    * a **NULL nem valid** érték
    + próbáljuk mindig ezt a változatot használni saját osztályokhoz, `std::string`-hez és STL adatszerkezetekhez
      ha paramétert nem akarjuk módosítani

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +A C++-ban érték szemantika van. Ez egy tiszta memóriaterület szeparációt tud eredményezni, de sokszor
"értékszemantika"

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +**RValue**: olyan kifejezés, mely nem LValue.
Nem értem mi a különbség

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +Eredmény: `S() S() copyCtr copy= copy=`
Ez sorrendet akar jelezni? Félreérthető

Eredmény:

```
S()       // S a
S()       // S b
copyStr   // T tmp(a)
copy=     // a = b
copy=     // b = tmp
```

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +Eredmény: `S() S() moveCtr move= move=`
```
S()       // S a
S()       // S b
moveCtr   // T tmp(std::move(a))
move=     // a = std::move(b)
move=     // b = std::move(tmp)
```

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +Hiba: Eljárás előfeltételének megsértése miatt, vagy bármely más nem kívánt működésből adódó állapot.
Ezt írnám helyette:

Hiba: program futása alatt bekövetkezett nemkívánt állapot. Két fajtáját különböztetjük meg:

* Logikai hiba (_logic error_): a program nem az elvárásnak megfelelő eredményt nyújtja, elő- vagy utófeltétel megsértése
* Futásidejű hiba (_runtime error_): rendszer állapotától függő hibás végrehajtás vagy megszakítás, mint például memória elfogyása, hibás IO, hibás hálózati kapcsolódás

Hibakezelés alatt a runtime error-okkal foglalkozunk.

(Forrás: https://stackoverflow.com/a/28095743)

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +Hiba: Eljárás előfeltételének megsértése miatt, vagy bármely más nem kívánt működésből adódó állapot.
Oké, ez a "nem kívánt állapot" még mindig gagyi, ha bedogjuk a közös code review-ba akkor biztos valakinek lesz jobb ötlete.

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +
\+

* hibakód változójának paraméterként való átadása referenciaként (klasszikus C-ben pointer)
* struct-al való visszatérés, mely az eredmény mellett tartalmazza a hibakódot is (mintha egy pair-ünk lenne)

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +* `assert()`: nem teljesül a feltétel $\Rightarrow$ hibaüzenet, mely a felhasználó számára nemigazán érthető
Légyszi légyszi, a "repülőpilótának nem bizalomgerjesztő egy ilyen üzenet" cuccot legalább egy zárójeles és dőltbetűs megjegyzésként írd oda, annyira imádom azt amit gsd mondott.

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +* `throw` - bármi dobható, de az értelmes: `std:exception` és annak leszármazottjai
(std::exception-t nem szívesen dobnak az emberek, akkor már inkább std::runtime_error-t)

* `throw` - bármi dobható, de az értelmes: `std:exception` leszármazottjai
    + Futásidejű hibákhoz: `std::runtime_error`
    + Logikai hibákhoz: `std::logic_error`

(Forrás: http://en.cppreference.com/w/cpp/error/exception)

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +}
Sorköz

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +    ```C++
Sorköz

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +    class X
(\newpage az fontos)

\newpage  

    + Ha tagváltozó inicializálása dob hibát, akkor dob a konstruktor is

```cpp
class X
{
    public:
        X()
        {
            throw std::runtime_error("Exception thrown from member.");
        }
};

class Y
{
    public:
        Y()
        try
            : x()   // You can have try-catch in initializer lists too
        { }
        catch( std::runtime_error& e )
        {
            throw e;  
        }

    private:
        X x;
};

int main()
{
    try
    {
        Y y;
        return 0;
    }
    catch ( std::runtime_error& e)
    {
        std::cerr << "exception: " << e.what() << std::endl;
    }
}
```

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +    ```C++
Ezt a kódpéldát nem értem.

2017-06-29 16:59 UTC, balintkiss501 commented on s02/2.md
> +        template <typename T>
Csinálj új sorközt és húzd a bekezdést balra, így pandoc-ban szebben fog kinézni, nem folyik össze az előző szöveggel.

2017-06-30 06:17 UTC, dobreffandras commented on s02/2.md
> +
Nem értek a C++-hoz, de a konstans pointer az nem így van: `f(int * const x)` ?

2017-06-30 06:23 UTC, dobreffandras commented on s02/2.md
> +**RValue**: olyan kifejezés, mely nem LValue.
Esetleg példával? Hogy LValue a `*++ptr` és a `*++qtr` is viszont az `a+5` az RValue?
De ebben nem vagyok biztos, elég homály nekem ez a rész. Ha `a+5` RValue, akkor ezek szerint ezt lehetne move-olni, ugye?

2017-06-30 06:26 UTC, dobreffandras commented on s02/2.md
> +Eredmény: `S() S() copyCtr copy= copy=`
Ezt írja ki a main, ha lefuttatod. 
Nem zavaró, hogy nem azt írja ki pontosan, amit te javasolsz? Jobban érthető, szóval támogatom.
Esetleg rakjuk bele mind a kettőt?

2017-06-30 06:39 UTC, dobreffandras commented on s02/2.md
> +        template <typename T>
Azt akartam elérni, hogy be legyen húzva, mert ugye a bullet point-hoz tartozik. Hülyén nézett ki, hogy a felsorolás beljebb van kezdve, a kódpélda meg teljesen a szélén.

2017-06-30 06:44 UTC, dobreffandras commented on s02/2.md
> +    ```C++
Írjunk magyarázatot?

* `noexcept( T::g() )` - operátor formás noexcept, megmondja, hogy `g` dob-e exception-t
* Ha igen, akkor `void f() noexcept(false)` lesz
* Ha nem dob, akkor `void f() noexcept(true)`
* tehát ha `g` nem dob, akkor `f` sem

2017-06-30 06:45 UTC, dobreffandras commented on s02/2.md
> +}
Mármint a záró kapcsos után, ugye?

2017-06-30 06:46 UTC, dobreffandras commented on s02/2.md
> +    ```C++
Itt hova gondoltad?

2017-06-30 08:11 UTC, balintkiss501 commented on s02/2.md
> +
https://stackoverflow.com/a/10091869

`int * const x`-nál nem maga a pointer konstans, hanem csak a változó értéke amire mutat (pointer on a constant value)

`const * int x`-nél maga a pointer a konstans, nem lehet módosítani hogy máshova mutasson. (constant pointer)

Jobban megnézve a "függvény nem módosítja a paramétert" akkor ilyenkor nem igaz, hacsak nem tisztázzuk mit értünk módosítás alatt, azt hogy mire mutat, vagy azt hogy mi az az érték amire mutat. Ha nem konstans pointer-t akartál, akkor írd át `const * int x`-et, de a fogalmak ne legyenek összekeverve.

2017-06-30 08:13 UTC, balintkiss501 commented on s02/2.md
> +**RValue**: olyan kifejezés, mely nem LValue.
Tegyél egy `**TODO**`-t és akkor kiegészítem.

2017-06-30 08:15 UTC, balintkiss501 commented on s02/2.md
> +Eredmény: `S() S() copyCtr copy= copy=`
Tegyél `<< std::endl`-t a kiíratások végére. Problem solved.

2017-06-30 08:17 UTC, balintkiss501 commented on s02/2.md
> +}
Igen, hogy legyen üres sor a foo meg a main függvény között.

2017-06-30 08:19 UTC, balintkiss501 commented on s02/2.md
> +}
```
struct ExceptionBase {
    virtual void raise() { throw *this; }
    virtual ~ExceptionBase() {}
};

struct ExceptionDerived : ExceptionBase {
    virtual void raise() { throw *this; }
};

void foo(ExceptionBase& e) {
    e.raise(); // Uses dynamic type of e while raising an exception.
}

int main (void) {
    ExceptionDerived e;
    try {
        foo(e);
    } catch (ExceptionDerived& e) {
        ...
    } catch (...) {
        ...
    }
}
```

2017-06-30 08:22 UTC, balintkiss501 commented on s02/2.md
> +    ```C++
```
    + Ha tagváltozó inicializálása dob hibát, akkor dob a konstruktor is

    class X
    {
        public:
            X() { throw 1; }
    };

   ...
```

2017-06-30 08:24 UTC, balintkiss501 commented on s02/2.md
> +    ```C++
Ez így jó, én így formáznám:

* `noexcept( T::g() )` - operátor formás `noexcept`, megmondja, hogy `g` dob-e exception-t
   + Ha igen, akkor `void f() noexcept(false)` lesz fordítás után
   + Ha nem dob, akkor `void f() noexcept(true)` fordítás után
   + tehát ha `g` nem dob, akkor `f` sem

2017-06-30 08:25 UTC, balintkiss501 commented on s02/2.md
> +        template <typename T>
Én simán a szélére tenném a kódrészletet.

2017-06-30 08:41 UTC, dobreffandras commented on s02/2.md
> +
Igen, kétértelmű a dolog.
Ez alapján írtam: http://www.cplusplus.com/articles/z6vU7k9E/
De ebben sem tiszta, hogy mit ért módosítás alatt. :/

2017-06-30 08:57 UTC, balintkiss501 commented on s02/2.md
> +
"2. Pass by const pointer when the value is expensive to copy AND the function does
not want to modify the value pointed to AND NULL is a valid, expected value that
the function handles."

Itt nem azt mondja, hogy "költséges a másolás", hanem hogy "használd ezt, ha az érték másolása költséges lenne".

Most látom én is félrenéztem, ezek a "költséges másolni" és "könnyű másolni" dolgok bezavartak nekem. Az egészet átírtam most:

* _érték szerinti_:
    + ```f(int x)```
    + a függvény **nem módosíthatja a paramétert**
    + használd ezt **ha könnyű másolni**
    + Ökölszabály: ha a paraméter mérete legfeljebb 2- vagy 3 szó (_word_), azaz 32-bit, akkor érdemes érték szerint átadni
        - egyszerű primitív típusok esetén ajánlott, mint pl.: `int`, `double`, `char`, `bool`, stb.
        - Komplex típusok, saját osztályok, `std::string` és a különböző STL konténerek nem ajánlottak (továbbiakban ezeket a példákban `T`-vel jelöljük)
* _pointer szerinti_:
    + ```f(T * x)```
    + a függvény **módosíthatja a paramétert**,
    + használd ezt, **ha költséges a másolás**,
    + továbbá akkor, ha **NULL lehet valid** érték
* _konstans pointer szerinti_:
    + ```f(const * T x)```
    + a függvény **módosíthatja az értéket amire mutat, de nem magát a pointert**,
    + használd ezt, **ha költséges a másolás**, 
    + továbbá akkor, ha **NULL lehet valid** érték
* _referencia szerinti_: 
    + ```f(T& x)```
    + a függvény **módosíthatja a paramétert**
    + használd ezt, **ha költséges a másolás**,
    + továbbá a **NULL NEM lehet valid** érték
    + használható kiementként is
* _konstans referencia szerinti_:
    + ```f(const T& x)```
    + a függvény **nem módosíthatja a paramétert**,
    + használd ezt, **ha költséges a másolás**
    + továbbá ha **NULL NEM lehet valid** érték
    + próbáljuk mindig ezt a változatot használni komplex típusokhoz, saját osztályokhoz, `std::string`-hez és STL adatszerkezetekhez a biztonságosabb programozás érdekében.
        - lásd még: copy konstruktorok, copy assignment-ek paraméterei

2017-06-30 10:03 UTC, dobreffandras commented
Ez a felsorolás+kódrészlet ez nem az igazi szerintem.

2017-06-30 10:11 UTC, balintkiss501 commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
Markdown-ban a {width=200px} szövegként jelenik meg.

2017-06-30 10:13 UTC, balintkiss501 commented on s02/2.md
> + S() { a = ++cnt; std::cout << “S() << std::endl”; }
`“S() << std::endl”` nincs. `“S()" << std::endl` van, rossz helyre került az idézőjel.

2017-06-30 10:13 UTC, dobreffandras commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
Igen, ha találsz módot arra, hogy meghatározzuk a kép méreteit és mindenhol jól jelenik meg, szólj ;-)

2017-06-30 10:18 UTC, balintkiss501 commented on s02/2.md
> +    + Ha tagváltozó inicializálása dob hibát, akkor dob a konstruktor is
\newpage miatt tényleg nem az igazi. Legyen akkor így, ne legyen bulletpoint-ban akkor:

#### Kivételkezelés és osztályok

Kérdéses esetek: konstruktor, destruktor

* Konstruktor
    + Ha a konstruktor dob, terület le lett foglalva, de a pointer nem lett beállítva $\Rightarrow$ nincs gond,
    a rendszer deallokálja
    + De: a konstruktoron belül lefogalt területet a destruktor tudja felszabadítani. A destruktort viszont nem lehet 
    meghívni mert az objektum létre se jött rendesen $\Rightarrow$ probléma
    
```C++
class X
{
    public:
        X(int i) { p = new char[i]; init(); }
        ~X() { delete [] p; }       // must not throw exception
    private:
        void init() { ... throw ... }   // BAD: destructor won't run !
        char *p;                        // constructor was not completed
    };
```

\newpage

Ha tagváltozó inicializálása dob hibát, akkor dob a konstruktor is
    
```C++
class X
{
    public:
        X() { throw 1; }
};

class Y
{
    public:
        Y()
        try
            : x()
        { }
        catch( ... ) { /* throw; */ }
    private:
        X x;
};

int main() {
    try {
        Y y;
        return 0;
    } catch (int i) {
        std::cerr << "exception: " << i << std::endl;
    }
}
```

2017-06-30 11:32 UTC, balintkiss501 commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
pandoc-ban nem írja ki? Nem tudok most generálni, nem otthon vagyok.

2017-06-30 11:33 UTC, balintkiss501 commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
Próbáld meg HTML-ben

<img src="img/referencia.png" alt="Referencia változók" style="width: 200px;"/>

2017-06-30 12:12 UTC, dobreffandras commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
Nekem így nem jelenik meg :/

2017-06-30 12:29 UTC, balintkiss501 commented on s02/2.md
> +![Referencia változók](img/referencia.png){width=200px}
Fene. Akkor maradjon az eredeti.

2017-06-30 15:17 UTC, balintkissdev approved these changes

2017-06-30 15:17 UTC, merged